config/routes.rb
# == Route Map
#
#       Prefix Verb   URI Pattern                   Controller#Action
#         root GET    /                             pages#home
#        pages GET    /pages(.:format)              pages#index
#              POST   /pages(.:format)              pages#create
#     new_page GET    /pages/new(.:format)          pages#new
#    edit_page GET    /pages/:id/edit(.:format)     pages#edit
#         page GET    /pages/:id(.:format)          pages#show
#              PATCH  /pages/:id(.:format)          pages#update
#              PUT    /pages/:id(.:format)          pages#update
#              DELETE /pages/:id(.:format)          pages#destroy
#        users GET    /users(.:format)              users#index
#              POST   /users(.:format)              users#create
#     new_user GET    /users/new(.:format)          users#new
#    edit_user GET    /users/:id/edit(.:format)     users#edit
#         user GET    /users/:id(.:format)          users#show
#              PATCH  /users/:id(.:format)          users#update
#              PUT    /users/:id(.:format)          users#update
#              DELETE /users/:id(.:format)          users#destroy
#    countries GET    /countries(.:format)          countries#index
#              POST   /countries(.:format)          countries#create
#  new_country GET    /countries/new(.:format)      countries#new
# edit_country GET    /countries/:id/edit(.:format) countries#edit
#      country GET    /countries/:id(.:format)      countries#show
#              PATCH  /countries/:id(.:format)      countries#update
#              PUT    /countries/:id(.:format)      countries#update
#              DELETE /countries/:id(.:format)      countries#destroy
#      results GET    /results(.:format)            countries#result
#      entries GET    /entries(.:format)            entries#index
#              POST   /entries(.:format)            entries#create
#    new_entry GET    /entries/new(.:format)        entries#new
#   edit_entry GET    /entries/:id/edit(.:format)   entries#edit
#        entry GET    /entries/:id(.:format)        entries#show
#              PATCH  /entries/:id(.:format)        entries#update
#              PUT    /entries/:id(.:format)        entries#update
#              DELETE /entries/:id(.:format)        entries#destroy
#        login GET    /login(.:format)              sessions#new
#              POST   /login(.:format)              sessions#create
#              DELETE /login(.:format)              sessions#destroy
#

Rails.application.routes.draw do
  root :to => 'pages#home'

  resources :pages

  resources :users
  resources :countries
  get '/results' => 'countries#result'
  resources :entries

  
  resources :locations

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/login' => 'sessions#destroy'
end

app/models/entry.rb
# == Schema Information
#
# Table name: entries
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  date       :date
#  entry      :text
#  image      :text
#  address    :string(255)
#  latitude   :float
#  longitude  :float
#  user_id    :integer
#  country_id :integer
#  created_at :datetime
#  updated_at :datetime
#

class Entry < ActiveRecord::Base
	belongs_to :country
	belongs_to :user

	geocoded_by :address
    after_validation :geocode
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
	def index
		@entries = Entry.all
		# binding.pry
	end

	def new
		@entry = Entry.new
	end

	def create
		entry = Entry.create! entry_params.merge(user_id: @current_user.id)
		redirect_to entry
	end

	# def create
	#     @entry = Entry.new user_params
	# 	#if 
	# 	@entry.save
	# 		entry[:country_id] = @country.id
	# 		redirect_to root_path
	# 		@entry.save
	# 	#else
	# 		#render: new
	# 	#end
	# end

	def edit
		@entry = Entry.find params[:id]
		@entry.save
	end

	def update
		entry = Entry.find params[:id]
		entry.update entry_params
		redirect_to entry
	end

	def show
		@entry = Entry.find params[:id]
	end

	def destroy
		entry = Entry.find params[:id]
		entry.destroy
		redirect_to entries_path
	end

	private
	def entry_params
		params.require(:entry).permit(:name, :date, :entry, :image, :address, :user_id, :country_id)
	end
end

app/views/entries/_form.html.erb
<%= form_for @entry do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name, :autofocus => true, :class => 'form-control' %>
  </div>
  <div>
    <%= f.label :date %>
    <%= f.date_field :date, :autofocus => true, :class => 'form-control' %>
  </div>
  <div class="entry">
    <%= f.label :entry%>
    <%= f.text_area :entry, :autofocus => true, :cols => "80", :rows => "5", :class => 'form-control' %>
  </div>
  <!-- <div>
    <%#= f.label :image %>
    <%#= f.text_field :image, :class => 'form-control' %>
  </div> -->
  <label></label>
  <div>
    <%= f.label :address %>
    <%= f.text_field :address, :size => 70, :class => "geocomplete" %>
  </div>
  <label></label>
  <div>
    <%= f.label :country %>
    <%= f.collection_select(:country_id, @current_user.countries, :id, :country, { :prompt => true }) %>
  </div>

  <%= f.submit :class => 'btn btn-default' %>
<% end %>

<script src="http://maps.googleapis.com/maps/api/js?sensor=false&amp;libraries=places"></script>
<script src="jquery.geocomplete.js"></script>
<script type="text/javascript">
  $("input.geocomplete").geocomplete();
</script>

app/views/entries/edit.html.erb
<h2>Edit Entry</h2>
<%= render :partial => 'form' %>

app/views/entries/index.html.erb
<div class="jumbotron">
	<% if @entries.present? %>
		<% @entries.each do |entry| %>
		  <li><%= entry.country.country if entry.country.present? %></li>
		  <li><%= link_to(entry.name, entry)%></li>
		  <hr class="featurette-divider">
		<% end %>
	<% else %>
		<p>There are no entries to display.</p>
		<hr class="featurette-divider">
	<% end %>  
</div

<!-- START THE FEATURETTES -->
<!-- 	<hr class="featurette-divider">

	<div class="row featurette">
	<div class="col-md-7">
	  <h2 class="featurette-heading">First featurette heading. <span class="text-muted">It'll blow your mind.</span></h2>
	  <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
	</div>
	<!-- IF I WANT TO ADD IMG BESIDE TEXT -->
	<!-- <div class="col-md-5">
	  <img class="featurette-image img-responsive" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
	</div> -->
<!-- 	</div>

	<hr class="featurette-divider">

	<div class="row featurette">

	<div class="col-md-7">
	  <h2 class="featurette-heading">Oh yeah, it's that good. <span class="text-muted">See for yourself.</span></h2>
	  <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
	</div>
	</div>

	<hr class="featurette-divider">

	<div class="row featurette">
	<div class="col-md-7">
	  <h2 class="featurette-heading">And lastly, this one. <span class="text-muted">Checkmate.</span></h2>
	  <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
	</div>
	</div>

	<hr class="featurette-divider"> -->

<!-- /END THE FEATURETTES -->

app/views/entries/new.html.erb
<h2>New Entry</h2>
<%= render :partial => 'form' %>

app/views/entries/show.html.erb
<div class="jumbotron">
	<h2><%= @entry.name %></h2>

	<article>
	  <header>
	  	<h3><%= @entry.address %></h3>
	  </header>
		<p>
			<%= @entry.entry %>
		</p>
		<p>
			<%= @entry.date %>	
		</p>
	</article>
	<%= link_to 'Edit', edit_entry_path(@entry) %>

	<%= link_to 'Delete', @entry, :method => :delete, :data => { :confirm => 'Are you sure?' }%>
</div>



<!-- <h3>Entries</h3>
<%# @entry.countries.each do |country| %>
  <%#= link_to country.title, country %>
<%# end %> -->