config/routes.rb
# == Route Map
#
#       Prefix Verb   URI Pattern                   Controller#Action
#         root GET    /                             pages#home
#        pages GET    /pages(.:format)              pages#index
#              POST   /pages(.:format)              pages#create
#     new_page GET    /pages/new(.:format)          pages#new
#    edit_page GET    /pages/:id/edit(.:format)     pages#edit
#         page GET    /pages/:id(.:format)          pages#show
#              PATCH  /pages/:id(.:format)          pages#update
#              PUT    /pages/:id(.:format)          pages#update
#              DELETE /pages/:id(.:format)          pages#destroy
#        users GET    /users(.:format)              users#index
#              POST   /users(.:format)              users#create
#     new_user GET    /users/new(.:format)          users#new
#    edit_user GET    /users/:id/edit(.:format)     users#edit
#         user GET    /users/:id(.:format)          users#show
#              PATCH  /users/:id(.:format)          users#update
#              PUT    /users/:id(.:format)          users#update
#              DELETE /users/:id(.:format)          users#destroy
#    countries GET    /countries(.:format)          countries#index
#              POST   /countries(.:format)          countries#create
#  new_country GET    /countries/new(.:format)      countries#new
# edit_country GET    /countries/:id/edit(.:format) countries#edit
#      country GET    /countries/:id(.:format)      countries#show
#              PATCH  /countries/:id(.:format)      countries#update
#              PUT    /countries/:id(.:format)      countries#update
#              DELETE /countries/:id(.:format)      countries#destroy
#      results GET    /results(.:format)            countries#result
#      entries GET    /entries(.:format)            entries#index
#              POST   /entries(.:format)            entries#create
#    new_entry GET    /entries/new(.:format)        entries#new
#   edit_entry GET    /entries/:id/edit(.:format)   entries#edit
#        entry GET    /entries/:id(.:format)        entries#show
#              PATCH  /entries/:id(.:format)        entries#update
#              PUT    /entries/:id(.:format)        entries#update
#              DELETE /entries/:id(.:format)        entries#destroy
#        login GET    /login(.:format)              sessions#new
#              POST   /login(.:format)              sessions#create
#              DELETE /login(.:format)              sessions#destroy
#

Rails.application.routes.draw do
  root :to => 'pages#home'

  resources :pages

  resources :users
  resources :countries
  get '/results' => 'countries#result'
  resources :entries

  
  resources :locations

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/login' => 'sessions#destroy'
end

app/views/pages/home.html.erb
<!-- <div class="jumbotron">
  <h1>Travel Trax</h1>
  <p>
  	Travel Trax is a personal travel blog allowing users to recored their travel itinirary and contact information privately and in one place. Sign up for free and start keeping track of your travels today.
  </p>
<!--   <p><a class="btn btn-primary btn-lg" role="button">Learn more</a></p> -->
</div>


<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Carousel Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Custom styles for this template -->
    <link href="carousel.css" rel="stylesheet">
  </head>

<body>
    <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        <div class="item active">
          <img src="http://www.vietlanddiscovery.com/wp-content/uploads/2013/07/200313_022720banner_1.jpg" alt="First slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Travel Trax</h1>
              <p>Travel Trax is a personal travel blog allowing users to recored their travel itinirary and contact information privately and in one place. Sign up for free and start keeping track of your travels today.</p>
              <p> <%= button_to('Sign up today', new_user_path, :method => :get, :class => "btn btn-lg btn-default") %></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img src="http://www.getdpi.com/gallery/files/1/3/0/1/alamogordo1_small.jpg" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Travel Trax</h1>
              <p>Travel Trax is a personal travel blog allowing users to recored their travel itinirary and contact information privately and in one place. Sign up for free and start keeping track of your travels today.</p>
			  <%= button_to('Sign up today', new_user_path, :method => :get, :class => "btn btn-lg btn-default") %>
            </div>
          </div>
        </div>
        <div class="item">
          <img src="http://oceanbluesky.com/wp-content/uploads/2013/12/Stephan-Kleinlein20130211-AO5A8268.jpg" alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Travel Trax</h1>
              <p>Travel Trax is a personal travel blog allowing users to recored their travel itinirary and contact information privately and in one place. Sign up for free and start keeping track of your travels today.</p>
			  <%= button_to('Sign up today', new_user_path, :method => :get, :class => "btn btn-lg btn-default") %>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
    </div><!-- /.carousel -->


      <!-- FOOTER -->
<!--       <footer>
        <p class="pull-right"><a href="#">Back to top</a></p>
        <p>&copy; 2014 TravelTrax, Inc. &middot;</p>
      </footer> -->

    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <script src="../../assets/js/docs.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>