config/routes.rb
# == Route Map
#
#       Prefix Verb   URI Pattern                   Controller#Action
#         root GET    /                             pages#home
#        pages GET    /pages(.:format)              pages#index
#              POST   /pages(.:format)              pages#create
#     new_page GET    /pages/new(.:format)          pages#new
#    edit_page GET    /pages/:id/edit(.:format)     pages#edit
#         page GET    /pages/:id(.:format)          pages#show
#              PATCH  /pages/:id(.:format)          pages#update
#              PUT    /pages/:id(.:format)          pages#update
#              DELETE /pages/:id(.:format)          pages#destroy
#        users GET    /users(.:format)              users#index
#              POST   /users(.:format)              users#create
#     new_user GET    /users/new(.:format)          users#new
#    edit_user GET    /users/:id/edit(.:format)     users#edit
#         user GET    /users/:id(.:format)          users#show
#              PATCH  /users/:id(.:format)          users#update
#              PUT    /users/:id(.:format)          users#update
#              DELETE /users/:id(.:format)          users#destroy
#    countries GET    /countries(.:format)          countries#index
#              POST   /countries(.:format)          countries#create
#  new_country GET    /countries/new(.:format)      countries#new
# edit_country GET    /countries/:id/edit(.:format) countries#edit
#      country GET    /countries/:id(.:format)      countries#show
#              PATCH  /countries/:id(.:format)      countries#update
#              PUT    /countries/:id(.:format)      countries#update
#              DELETE /countries/:id(.:format)      countries#destroy
#      results GET    /results(.:format)            countries#result
#      entries GET    /entries(.:format)            entries#index
#              POST   /entries(.:format)            entries#create
#    new_entry GET    /entries/new(.:format)        entries#new
#   edit_entry GET    /entries/:id/edit(.:format)   entries#edit
#        entry GET    /entries/:id(.:format)        entries#show
#              PATCH  /entries/:id(.:format)        entries#update
#              PUT    /entries/:id(.:format)        entries#update
#              DELETE /entries/:id(.:format)        entries#destroy
#        login GET    /login(.:format)              sessions#new
#              POST   /login(.:format)              sessions#create
#              DELETE /login(.:format)              sessions#destroy
#

Rails.application.routes.draw do
  root :to => 'pages#home'

  resources :pages

  resources :users
  resources :countries
  get '/results' => 'countries#result'
  resources :entries

  
  resources :locations

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/login' => 'sessions#destroy'
end

app/models/country.rb
# == Schema Information
#
# Table name: countries
#
#  id         :integer          not null, primary key
#  country    :string(255)
#  created_at :datetime
#  updated_at :datetime
#  user_id    :integer
#

class Country < ActiveRecord::Base
	has_many :entries
	belongs_to :user
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
	def index
		@countries = @current_user.countries
	end

	def new
		@country = Country.new
	end

	def create
		country = Country.new country_params
		country.user = @current_user
		country.save
		redirect_to country
	end

	def edit
		@country = Country.find params[:id]
	end

	def update
		country = Country.find params[:id]
		country.update country_params
		redirect_to country
	end

	def show
		@country = Country.find params[:id]
	end

	def result
		location = params[:location]
		@result = Geocoder.search(location).first
	end

	def destroy
		country = Country.find params[:id]
		country.destroy
		redirect_to country
	end

	private
	def country_params
		params.require(:country).permit(:country)
	end
end

app/views/countries/_form.html.erb
<!--   <div class="field">
    <%#= f.label :country %>
    <%#= f.country_select :country, prompt: 'Please select a country' %>
  </div>  -->


<%= form_for @country do |f| %>
  <div>
  	<%#= f.label :country, prompt: 'Please select a country' %>
    <label>Please select a country</label>
    <%= f.text_field :country, :class => 'form-control' %>
  </div>
  <%= f.submit :class => 'btn btn-default'  %>
<% end %> 

app/views/countries/edit.html.erb
<h2>Edit Country</h2>
<%= render :partial => 'form' %>

app/views/countries/index.html.erb
<!-- <div class="jumbotron">
<#% @countries.each do |country| %>
	<ul>
		<!-- <li><%#= image_tag(country.image, :class => 'thumbnail') %></li> -->
		<!-- <li><%#= link_to(country.country, country)%></li>
	</ul>
<%# end %>
</div> -->
<div class="jumbotron">
	<% @countries.each do |country| %>
		<h3><%= link_to(country.country, country)%></h3>
		<hr class="featurette-divider">
	<% end %>
</div>

app/views/countries/new.html.erb
<%= render :partial => 'form' %>

app/views/countries/result.html.erb
<!-- <h2>view maps</h2> -->
<%#= form_tag '/results', :method => :get do %>
  <%#= text_field_tag(:location, nil, :placeholder => 'Which location?') %>
  <%#= submit_tag('Go') %>
<%# end %>

app/views/countries/show.html.erb
<h2><%= @country.country %></h2>
<%#= image_tag @country.image %>

<%= link_to 'Edit', edit_country_path(@country) %>
<%= link_to 'Delete', @country, :method => :delete, :data => { :confirm => 'Are you sure? This will delete all posts written for this country.' } %>


<% if @country.entries.present? %>
  <article>
    <% @country.entries.each do |entry| %>
      <header>
      	<h1><%= link_to entry.name, entry %></h1>
      	<h3><%= entry.address %></h2>
      </header>
    	<p>
    		<%= entry.entry %>
    	</p>
      <p>
        Date of travel: <%= entry.date %>
      </p>
    <% end %>
    <hr class="featurette-divider">
  </article>
<% else %>
	<p>There are no entries to display.</p>
<% end %>